<a href="https://colab.research.google.com/github/sawroooz/handson-ml2/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
car=np.array([1,2,3,4,5])
print(np.max(car))

5


In [2]:
np1=np.array([1,2,3,4,5])
print(np.sin(np1))
print(np.log(np1))
print(np.sqrt(np1[3]))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
2.0


In [4]:
np2=np.array([1,2,3,4])
print(np2[:])


[1 2 3 4]


In [8]:
np3=np.array([1,3,4,-3,4])
np4=np3.copy()
print(f'original value{np3}')
print(f'changed value{np4}')
np4[3]=27
print(f'original value{np3}')
print(f'changed value{np4}')


original value[ 1  3  4 -3  4]
changed value[ 1  3  4 -3  4]
original value[ 1  3  4 -3  4]
changed value[ 1  3  4 27  4]


In [10]:
lists=[1,2,3,4]
np5=np.array(lists)
print(np5)

[1 2 3 4]


In [12]:
np5=np.array([[1,2,3,4],[1,4,-4,5]])
print(np5[1,3])

5


In [14]:
np6=np.array([[1,2,3,4,5,],[6,7,8,9,1]])
print(np6)
print(np6.shape)
np7=np6.reshape(5,2)
print(np7)
print(np7.shape)

[[1 2 3 4 5]
 [6 7 8 9 1]]
(2, 5)
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]]
(5, 2)
